name: generate animation

on:
  # 24시간마다 자동으로 실행
  schedule:
    - cron: "0 */24 * * *" 
  
  # 수동으로도 실행 가능하게 설정
  workflow_dispatch:
  
  # master 브랜치에 push가 발생할 때마다 실행
  push:
    branches:
    - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # GitHub 기여도 그래프를 기반으로 애니메이션 생성
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: jinseok19
          outputs: |
            # 사이버펑크 스타일: 네온 핑크 뱀 + 일렉트릭 블루/시안 잔디
            dist/github-contribution-grid-snake.svg?color_snake=#ff00ff&color_dots=#161b22,#003366,#006699,#00ffff,#00ffcc
            
            # 다크 모드용: 형광 연두 뱀 + 딥 퍼플/화이트 잔디
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#adff2f&color_dots=#161b22,#4b0082,#8a2be2,#d8bfd8,#ffffff
            
      # 생성된 SVG 파일을 'output' 브랜치로 푸시
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
